### ISSUE TITLE
It should be possible to load scripts in the defined order

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/react-loaders#1]
In current implementation scripts which are passed to ScriptsLoaderContainer are loaded asynchronously and as the result order is not preserved. This can be achieved by adding attribute async="false" to tag <script>.

**Comment by apyrkh-sc** [comment]
Have the same issue. Please fix it

**Comment by kvolkovich-sc** [comment]
Added boolean `sync` property to ScriptsLoaderContainer. Please try v0.1.6.
If it's works properly, please close this issue.

**Comment by kvolkovich-sc** [comment]
Fixed bug reported by @apechenko-sc reported a bug. Please try v0.1.7.

**Comment by apechenko-sc** [comment]
That's exactly what I needed. Thanks.
