### ISSUE TITLE
Option to specify the component name

### ISSUE THREAD

**Issue by lakshgoel95** [OpusCapita/react-loaders#4]
https://github.com/OpusCapita/react-loaders/blob/master/src/client/components/serviceComponent/serviceComponent.react.js#L22

In case more than one components are being exported from a file there should be an option to specify which component to render.

Let me know, whether this one is a valid enhancement or not.

**Comment by asergeev-sc** [comment]
@lakshgoel95 It looks like **componentPath** option **serviceComponent** should cover your case

**Comment by kvolkovich-sc** [comment]
Closed because of outdate. If issue hasn't been resolved, you can reopen the issue.
